[package]
name = "haystack"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
pulldown-cmark = "0.13.0"
tiny_http = "0.12"
walkdir = "2.5"
orgize = "0.9"
