name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build binary
        run: cargo build --release

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/haystack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
